export const ADD_PHOTO_LIST = "ADD_PHOTO_LIST";
export const ADD_FAVORITE_LIST = "ADD_FAVORITE_LIST";
export const ADD_FAVORITE_PHOTO = "ADD_FAVORITE_PHOTO";
export const REMOVE_FAVORITE_PHOTO = "REMOVE_FAVORITE_PHOTO";
export const SET_PHOTO_PAGE = "SET_PHOTO_PAGE";
export const SET_PHOTO_AMOUNT = "SET_PHOTO_AMOUNT";